In [1]:
from inference import GPT,GPTConfig,CausalSelfAttention,MLP,Block
import torch

In [2]:
t=torch.randn(1,3,768)
m=CausalSelfAttention(GPTConfig)
m1=MLP(GPTConfig)

In [3]:
x,a1,a=m(
    t
)
print(x)

tensor([[[ 0.0571, -0.0147,  0.2563,  ...,  0.1437,  0.2194,  0.0089],
         [ 0.1043,  0.0443,  0.0722,  ...,  0.1402,  0.1269, -0.0184],
         [ 0.2369, -0.1305,  0.0259,  ...,  0.2407,  0.1699,  0.1115]]],
       grad_fn=<ViewBackward0>)


In [4]:
for i in range(1,3+1):
    x1,a2,a21=m(
        t[:,i-1:i],kv_cache=True,steps=i-1
    )

    print(a1[:,0,:],a2[:,1,:],sep='\n')

tensor([[[-0.5529,    -inf,    -inf],
         [ 0.3830, -0.0220,    -inf],
         [ 0.1039,  0.2525,  0.2083]]], grad_fn=<SliceBackward0>)
tensor([[[0.6674]]], grad_fn=<SliceBackward0>)
tensor([[[-0.5529,    -inf,    -inf],
         [ 0.3830, -0.0220,    -inf],
         [ 0.1039,  0.2525,  0.2083]]], grad_fn=<SliceBackward0>)
tensor([[[0.0128, 0.2662]]], grad_fn=<SliceBackward0>)
tensor([[[-0.5529,    -inf,    -inf],
         [ 0.3830, -0.0220,    -inf],
         [ 0.1039,  0.2525,  0.2083]]], grad_fn=<SliceBackward0>)
tensor([[[-0.6409, -0.1511,  0.1725]]], grad_fn=<SliceBackward0>)


In [ ]:
a